### ISSUE TITLE
The mod does not work with me but with the Host please help

### ISSUE THREAD

**Issue by Joris587** [Felix-Puetz/raft-mods#2]

**Comment by flx-sta** [comment]
@Joris587 did you both have the mod installed?

**Comment by CRSmith15** [comment]
some friends and I are also having this issue. All three of  us have it installed, but its only works for me (the host) and one other person. For some reason the third person to join just doesn't get it.

**Comment by flx-sta** [comment]
@CRSmith15 hm.. okay so you say the 3rd Person has this issue.
That explains why I couldn't  reproduce it yet. Only tested with 2.
That is unfortunate. 
I'll look into it will have to hook up some friends to able to though.
thanks for the info
