### ISSUE TITLE
It does not load, still stuck on 1.08, I installed it 3 times

### ISSUE THREAD

**Issue by spelcy226** [Felix-Puetz/raft-mods#4]

**Comment by flx-sta** [comment]
@spelcy226 can you provide me the logs?

**Comment by flx-sta** [comment]
If you name on discord is `PAPI` (with weired square around it) I've just patched it. only a visual bug apparently

**Comment by spelcy226** [comment]
Oh ok, thank you

**Comment by spelcy226** [comment]
My name is Lorellai-Kul tiras btw

**Comment by spelcy226** [comment]
Ok, tried downloading it again and it did update, but now this happens
[image: Untitled.png]


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by flx-sta** [comment]
I cannot open that image. Just a link to avast anti virus
