### ISSUE TITLE
Mod 1.2b needs update?

### ISSUE THREAD

**Issue by KyrinFireheart** [Felix-Puetz/raft-mods#5]
Every time I start the game I get a message stating that Almost No Durability has a new version available and when I hover over the mod on the mod list it shows out of date. But when I download from the website or from the discord it's the same version I already have. Is there a new version or is the mod version number not updated?

Would also really love it if you could add the flippers, mining helmet and even the body armor to the list since those take damage so quickly under the normal rule set.

**Comment by flx-sta** [comment]
@KyrinFireheart Happy New Year.

> Every time I start the game I get a message stating that Almost No Durability has a new version available and when I hover over the mod on the mod list it shows out of date. But when I download from the website or from the discord it's the same version I already have. Is there a new version or is the mod version number not updated?

Could you show me what versions it is showing on the server and what version you downloaded?

> Would also really love it if you could add the flippers, mining helmet and even the body armor to the list since those take damage so quickly under the normal rule set.

Didn't know they were not Included. Thanks for the notice. I'll look into it 👍 
Move that into #6

**Comment by KyrinFireheart** [comment]
It shows 1.2b for the one in game. I also downloaded 1.2b from both the
link in discord and directly from searching the website.

**Comment by flx-sta** [comment]
probably an issue with the fact that i realeased that version 2 times.
Likely will be fixed in the next patch 👍

**Comment by KyrinFireheart** [comment]
Cool, thanks!

**Comment by flx-sta** [comment]
New release is up
