### ISSUE TITLE
Change item durability 

### ISSUE THREAD

**Issue by tmraihan** [Felix-Puetz/raft-mods#7]
instead have 0 durability, can i change the durability? for example make item 2 times more durable? 

its not bug by the way, thank you

**Comment by flx-sta** [comment]
@tmraihan you want to configurable basically?

**Comment by tmraihan** [comment]
yes thats what i mean

thank you

**Comment by flx-sta** [comment]
puh. ill have to think about this. maybe in the future. not right now

**Comment by tmraihan** [comment]
ok ok, thank you for the mod btw

**Comment by flx-sta** [comment]
I tried extending the settings menu to be able to provide a slider but without success. Won't be putting any more time into this for now, sorry

**Comment by flx-sta** [comment]
@tmraihan In the most recent version (3.0.0) I've added a setting to change the durability from infinite to 2x - 10x

you have to have a other mod to change this though! just check the readme
