### ISSUE TITLE
Durability of food affected?

### ISSUE THREAD

**Issue by LoganMcGoats** [Felix-Puetz/raft-mods#8]
I may be very stupid, as is often the case, so I apologize if I missed something very obvious and am wasting your time. This mod seems to affect the durability of food, too. I know it is this mod (my food was back to normal consumption/disappearing from my inventory after one use when I unloaded this mod). I think this mod is supposed to just be for tools/equipment so we can still have the survival sense, right? Is there a setting I am being completely blind to? Or did I simply misunderstand what this mod's objective was? I hate having to replace my hook/spear every 3 seconds but I still want the threat of starving/dehydrating to be a factor. Thank you in advance!

**Comment by itje4u** [comment]
I have this issue too (I think it was not there last week)

**Comment by TrollanKojima** [comment]
Same issue. Seems to be affecting anything that has a "use" that isn't crafting.
Example: If I set it to 3x, I get 3 uses out of a metal ore before it expends the ore in the smelter. I make a cooked potato, I get 3 uses out of it. I spent half an hour trying to figure out what in my mods could be causing it before I realized I had my durability set to 3x.

**Comment by flx-sta** [comment]
Thanks for the notice.

In fact that's a bug caused by my most recent version. I'll not get into detail what exactly causes this but let's say it's not super easy to solve unfortunately.
I'm looking into it but can't promise anything.
If it ruins your experience please feel free to roll-back to the old version 👍

**Comment by LoganMcGoats** [comment]
Thank you for the reply, @Felix-Puetz and a great mod. Yeah, don't worry about explaining the actual issue in detail. I am extremely dumb about game code and modding so it would go right over my head. I remember before mod loaders could basically download pre-made mods for me....I broke Minecraft so many times haha. On that note of my uselessness, how do I go about rolling back to a previous version?

**Comment by flx-sta** [comment]
@LoganMcGoats 
you start the mod loader, open the mods folder via the button at the bottom right and remove the new mod.

Then on the website there is a versions menu: https://www.raftmodding.com/mods/almost-no-durability/versions

There you download the previous one. And put it manually into the same folder where you removed the newer one.

**Comment by LoganMcGoats** [comment]
@Felix-Puetz Thank you so much!

**Comment by flx-sta** [comment]
@LoganMcGoats @itje4u @TrollanKojima 
This bug has been fixed. Thanks alot for making me aware of it 👍 
https://github.com/Felix-Puetz/raft-mods/commit/07ab6713c17cfab6a6badb4b4e454196e4c8a43b

**Comment by LoganMcGoats** [comment]
Oh fantastic! Thank you for the amazing work!

**Comment by itje4u** [comment]
The bug is not totally fixed, when I put seaweed in a smelter I keep the same amount of seaweed in my inventory, so I now have infinite seaweed lol (not very bothersome, just thought id let you know!)
